datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./database"
  production:
    username: ${Username}
    password: ${Password}
    url: jdbc:postgresql://${Hostname}:${Port}/${page_analyzer_db}

ebean:
  development:
    migration:
      run: true
  production:
    migration:
      run: true