datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./database"
  production:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

ebean:
  development:
    migration:
      run: true
  production:
    migration:
      run: true